apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  namespace: camel-rotta
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""  # esplicitamente vuoto per matchare PVC
  hostPath:
    path: /tmp
    type: ""
