apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-hostpath-volume-rwx
  namespace: camel-rotta
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /tmp/shared