apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: camel-rotta
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: shared-pv
