apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: camel-rotta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: thin-csi
