apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: camel-rotta
  name: bind-configmap-and-job-manager
subjects:
  - kind: ServiceAccount
    name: camel-job-sa
    namespace: camel-rotta
roleRef:
  kind: Role
  name: configmap-and-job-manager
  apiGroup: rbac.authorization.k8s.io
