apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: camel-rotta
  name: configmap-and-job-manager
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
