apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: camel-rotta
  name: cronjob-trigger-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
