apiVersion: v1
kind: Pod
metadata:
  name: rsh-pod
  namespace: camel-rotta
spec:
  containers:
    - name: rsh-container
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command: ["sleep", "3600"]
      volumeMounts:
        - name: shared-pvc
          mountPath: /tmp/shared
  volumes:
    - name: shared-pvc
      persistentVolumeClaim:
        claimName: shared-pvc